package Buku;

import com.formdev.flatlaf.FlatClientProperties;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import Navbar.koneksi;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Logger;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;


public class Buku extends javax.swing.JPanel {
    private Connection con;
    private PreparedStatement pst, pst1;
    private ResultSet rs;
    private String kode_buku;
    private String No_buku;
    private int noBukuEdit = -1;
    
    public Buku() throws SQLException {
        con = koneksi.Koneksi();
        initComponents();
        loadTabel();
        jPanel1.putClientProperty(FlatClientProperties.STYLE, "arc:30");
        jPanel2.putClientProperty(FlatClientProperties.STYLE, "arc:30");
        jPanel3.putClientProperty(FlatClientProperties.STYLE, "arc:30");
        UIManager.put("Button.arc", 15);
        txt_search.putClientProperty("JComponent.roundRect", true);
        JTabel1.getTableHeader().setBackground(new Color(63, 148, 105));
        JTabel1.getTableHeader().setForeground(Color.white);
        JTabel1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        Jdialog.setSize(570, 514);
    }
    
    private void Jdialog () {
        Jdialog.setLocationRelativeTo(null);
        Jdialog.setBackground(Color.white);
        Jdialog.getRootPane().setOpaque(false);
        Jdialog.getContentPane().setBackground(new Color(0, 0, 0, 0));
        Jdialog.setBackground(new Color(0, 0, 0, 0));
    }
    private void jcombo() {
        if (dial_kategori.getSelectedItem() == null) {
            dial_kategori.setSelectedItem("Kategori Buku");
        }
    }
    

    private void loadTabel() throws SQLException {
        JTabel1.clearSelection();
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
        model.addColumn("No");
        model.addColumn("Kode Buku");
        model.addColumn("Judul Buku");
        model.addColumn("Jilid");
        model.addColumn("Kategori ");
        model.addColumn("Pengarang");
        model.addColumn("Lokasi");
        model.addColumn("Kondisi");
        model.addColumn("Tahun Terbit");  
        model.addColumn("Asal Buku");
        model.addColumn("Harga");
        model.addColumn("Stock");

        try {
            pst = con.prepareStatement("SELECT * FROM buku");
            rs = pst.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString("No_buku"), rs.getString("kode_buku"), rs.getString("judul_buku"), rs.getString("jilid"), rs.getString("kategori"), rs.getString("pengarang"), rs.getString("lokasi"),rs.getString("kondisi_buku"),rs.getInt("tahun_terbit"),rs.getString("asal_buku"),rs.getInt("harga"),rs.getInt("jumlah_stock")});
            }
            JTabel1.setModel(model);
        } catch (Exception e) {
            System.out.println("loadTable" + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jdialog = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dial_kode = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        dial_judul = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        dial_jilid = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        dial_pengarang = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        dial_lokasi = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        dial_tahun = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        dial_asal = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        dial_harga = new javax.swing.JTextField();
        dial_kondisi = new javax.swing.JComboBox<>();
        btn_simpan = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        dial_stock = new javax.swing.JTextField();
        btn_cancel = new javax.swing.JButton();
        dial_kategori = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTabel1 = new javax.swing.JTable();
        btn_tambah = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        Jdialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Jdialog.setUndecorated(true);
        Jdialog.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JdialogFocusLost(evt);
            }
        });
        Jdialog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JdialogKeyPressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setMaximumSize(new java.awt.Dimension(649, 649));
        jPanel2.setMinimumSize(new java.awt.Dimension(649, 649));

        jPanel3.setBackground(new java.awt.Color(63, 148, 105));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TAMBAH BUKU");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(389, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Kode Buku");

        dial_kode.setMaximumSize(new java.awt.Dimension(570, 73));
        dial_kode.setMinimumSize(new java.awt.Dimension(570, 73));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Judul Buku");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Jilid");

        dial_jilid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dial_jilidActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("Kategori");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setText("Pengarang");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("Lokasi");

        dial_lokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dial_lokasiActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setText("Kondisi");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setText("Tahun Terbit");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setText("Asal Buku");

        dial_asal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dial_asalActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setText("Harga");

        dial_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dial_hargaActionPerformed(evt);
            }
        });

        dial_kondisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baik", "Rusak", "Hilang" }));
        dial_kondisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dial_kondisiActionPerformed(evt);
            }
        });

        btn_simpan.setBackground(new java.awt.Color(63, 148, 105));
        btn_simpan.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_simpan.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpan.setText("SIMPAN");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Stock");

        dial_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dial_stockActionPerformed(evt);
            }
        });

        btn_cancel.setBackground(new java.awt.Color(204, 0, 51));
        btn_cancel.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancel.setText("CANCEL");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        dial_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendidikan", "Non Pendidikan" }));
        dial_kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dial_kategoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dial_jilid)
                            .addComponent(dial_judul)
                            .addComponent(dial_pengarang)
                            .addComponent(dial_kode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dial_kategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(dial_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(dial_asal, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dial_tahun, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dial_kondisi, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(dial_lokasi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_cancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_simpan))
                            .addComponent(dial_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dial_kode, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dial_lokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dial_judul, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dial_kondisi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dial_jilid, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dial_tahun, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dial_asal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dial_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dial_pengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dial_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dial_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JdialogLayout = new javax.swing.GroupLayout(Jdialog.getContentPane());
        Jdialog.getContentPane().setLayout(JdialogLayout);
        JdialogLayout.setHorizontalGroup(
            JdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 570, Short.MAX_VALUE)
        );
        JdialogLayout.setVerticalGroup(
            JdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 514, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(204, 204, 204));
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("LIST DATA BUKU");

        txt_search.setToolTipText("");
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        JTabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JTabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode Buku", "Judul Buku", "Jilid", "Kategori", "Pengarang", "Lokasi", "Kondisi ", "Tahun Terbit", "Asal Buku", "Harga", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTabel1.setGridColor(new java.awt.Color(0, 0, 0));
        JTabel1.setShowGrid(true);
        JTabel1.getTableHeader().setReorderingAllowed(false);
        JTabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTabel1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTabel1);
        if (JTabel1.getColumnModel().getColumnCount() > 0) {
            JTabel1.getColumnModel().getColumn(0).setResizable(false);
            JTabel1.getColumnModel().getColumn(1).setResizable(false);
            JTabel1.getColumnModel().getColumn(2).setResizable(false);
            JTabel1.getColumnModel().getColumn(3).setResizable(false);
            JTabel1.getColumnModel().getColumn(4).setResizable(false);
            JTabel1.getColumnModel().getColumn(5).setResizable(false);
        }

        btn_tambah.setBackground(new java.awt.Color(63, 148, 105));
        btn_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_15/image_button/+.png"))); // NOI18N
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_edit.setBackground(new java.awt.Color(255, 227, 130));
        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_15/image_button/edit_1160515 3.png"))); // NOI18N
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_hapus.setBackground(new java.awt.Color(255, 145, 66));
        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_15/image_button/trash-can_7343703 2.png"))); // NOI18N
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Search");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addContainerGap())
        );

        txt_search.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        dial_kode.setText(null);
        dial_judul.setText(null);
        dial_jilid.setText(null);
        dial_kategori.setSelectedItem(null);
        dial_pengarang.setText(null);
        dial_lokasi.setText(null);
        dial_kondisi.setSelectedItem(null);
        dial_tahun.setText(String.valueOf(""));
        dial_asal.setText(null);
        dial_harga.setText(String.valueOf(""));
        dial_stock.setText(String.valueOf(""));
        dial_kode.setEnabled(true);
        noBukuEdit=-1;
        
        Jdialog.setVisible(true);
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
//        get index table selected
        int row = JTabel1.getSelectedRow();
        System.out.println("index "+row);
//        cek jika tidak ada row yang diselect
        if (row < 0) {
            JOptionPane.showMessageDialog(jPanel2, "Pilih Dahulu Data Yang Akan Di Ubah");
        }
        try {
            //get data dari table  berdasarkan row index dan colom keberapa
            //0 index colom no buku
            int noBuku = Integer.parseInt((String) JTabel1.getValueAt(row, 0));
            pst = con.prepareStatement("SELECT * FROM buku WHERE No_buku = '"+noBuku+"'");
            rs = pst.executeQuery();
            rs.next();
            System.out.println(noBuku);
            String kode_buku = rs.getString("kode_buku");
            String judul_buku = rs.getString("judul_buku");
            String jilid = rs.getString("jilid");
            String kategori = rs.getString("kategori");
            String pengarang = rs.getString("pengarang");
            String lokasi = rs.getString("lokasi");
            String kondisi_buku = rs.getString("kondisi_buku");
            Date tahun_terbit = rs.getDate("tahun_terbit");
            Format formater = new SimpleDateFormat("yyyy");
            String tahunterbit = formater.format(tahun_terbit);
            String asal_buku = rs.getString("asal_buku");
            int harga = rs.getInt("harga");
            int jumlah_stock = rs.getInt("jumlah_stock");

            dial_kode.setText(kode_buku);
            dial_judul.setText(judul_buku);
            dial_jilid.setText(jilid);
            dial_kategori.setSelectedItem(kategori);
            dial_pengarang.setText(pengarang);
            dial_lokasi.setText(lokasi);
            dial_kondisi.setSelectedItem(kondisi_buku);
            dial_tahun.setText(String.valueOf(tahunterbit));
            dial_asal.setText(asal_buku);
            dial_harga.setText(String.valueOf(harga));
            dial_stock.setText(String.valueOf(jumlah_stock));
            dial_kode.enable(false);
            noBukuEdit = noBuku;
            Jdialog.setVisible(true);
        } catch (Exception e) {
            System.out.println("click" + e.getMessage());
            JOptionPane.showMessageDialog(jPanel2, "Pilih Dahulu Data Yang Akan Di Ubah");
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        DefaultTableModel model = (DefaultTableModel) JTabel1.getModel();
        int selectedRowIndex = JTabel1.getSelectedRow();
        if (selectedRowIndex != -1) { // Pastikan baris yang dipilih tidak kosong
            // Ambil nilai dari kolom No_buku pada baris yang dipilih
            int No_buku = Integer.parseInt(model.getValueAt(selectedRowIndex, 0).toString());

            // Tampilkan dialog konfirmasi
            int dialogResult = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus buku dengan No Buku " + No_buku + "?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

            if (dialogResult == JOptionPane.YES_OPTION) {
                try {
                    // Buat koneksi ke database
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3307/perpusmu", "root", "");

                    // Buat pernyataan SQL DELETE
                    String sql = "DELETE FROM buku WHERE No_buku = ?";
                    PreparedStatement pst = con.prepareStatement(sql);
                    pst.setInt(1, No_buku);

                    // Eksekusi pernyataan DELETE
                    pst.executeUpdate();

                    // Hapus baris dari model tabel
                    model.removeRow(selectedRowIndex);
                } catch (Exception e) {
            System.out.println("click" + e);
            JOptionPane.showMessageDialog(jPanel2, "Pilih Dahulu Data Yang Akan Di Hapus");
        }
            }
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        String kode_buku = dial_kode.getText();
        String judul_buku = dial_judul.getText();
        String jilid = dial_jilid.getText();
        Object kategori = dial_kategori.getSelectedItem();
        String pengarang = dial_pengarang.getText();
        String lokasi = dial_lokasi.getText();
        Object kondisi_buku = dial_kondisi.getSelectedItem();
        int tahun_terbit = Integer.parseInt(dial_tahun.getText());
        String asal_buku = dial_asal.getText();
        int harga = Integer.parseInt(dial_harga.getText());
        int jumlah_stock = Integer.parseInt(dial_stock.getText());

        if (kode_buku == null || judul_buku == null || jilid == null || kategori == null || pengarang == null || lokasi == null || kondisi_buku == null || tahun_terbit == -1 || asal_buku == null || harga == -1 || jumlah_stock == -1) {
            JOptionPane.showMessageDialog(Jdialog, "Anda Harus Mengisi Semua Data Terlebih Dahulu");
        } else {
            int result = JOptionPane.showConfirmDialog(Jdialog, "Apakah Anda Ingin Menyimpan?", "Konfirmasi",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if (result == JOptionPane.YES_OPTION) {
                try {
                    pst = con.prepareStatement("SELECT * FROM buku WHERE No_buku = ?");
                    pst.setString(1, String.valueOf(noBukuEdit));
                    rs = pst.executeQuery();
                    if (rs.next()) {
                        pst = con.prepareStatement("UPDATE buku SET kode_buku = ?, judul_buku = ?, jilid = ?, kategori = ?, pengarang = ?, lokasi = ?, kondisi_buku = ?, tahun_terbit = ?, asal_buku = ?, harga =?, jumlah_stock = ? WHERE No_buku = ?");
                        pst.setString(1, kode_buku);
                        pst.setString(2, judul_buku);
                        pst.setString(3, jilid);
                        pst.setString(4, (String) kategori);
                        pst.setString(5, pengarang);
                        pst.setString(6, lokasi);
                        pst.setString(7, (String) kondisi_buku);
                        if (tahun_terbit != 0) {
                            pst.setInt(8, tahun_terbit);
                        } else {
                            pst.setNull(8, java.sql.Types.INTEGER);
                        }
                        pst.setString(9, asal_buku);
                        if (harga != 0) {
                            pst.setInt(10, harga);
                        } else {
                            pst.setNull(10, java.sql.Types.INTEGER);
                        }
                        if (jumlah_stock != 0) {
                            pst.setInt(11, jumlah_stock);
                        } else {
                            pst.setNull(11, java.sql.Types.INTEGER);
                        }
                        
                          pst.setInt(12, noBukuEdit);
                        pst.executeUpdate();
                        noBukuEdit=-1;

                    } else {
                        try {
                            pst1 = con.prepareStatement("Insert into buku (kode_buku, judul_buku, jilid, kategori, pengarang, lokasi, kondisi_buku, tahun_terbit, asal_buku, harga, jumlah_stock) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
                            pst1.setString(1, kode_buku);
                            pst1.setString(2, judul_buku);
                            pst1.setString(3, jilid);
                            pst1.setString(4, (String) kategori);
                            pst1.setString(5, pengarang);
                            pst1.setString(6, lokasi);
                            pst1.setString(7, (String) kondisi_buku);
                            pst1.setInt(8, tahun_terbit);
                            pst1.setString(9, asal_buku);
                            pst1.setInt(10, harga);
                            pst1.setInt(11, jumlah_stock);
                            pst1.executeUpdate();
                        } catch (Exception r) {
                            System.out.println("insert simpan " + r); 
                        }
                    }
                    
                    loadTabel();
                } catch (Exception e) {
                    System.out.println("No_buku buku" + e.getMessage());
                }
                
                Jdialog.dispose();
            }
        }


    }//GEN-LAST:event_btn_simpanActionPerformed

    private void dial_lokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dial_lokasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dial_lokasiActionPerformed

    private void dial_kondisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dial_kondisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dial_kondisiActionPerformed

    private void dial_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dial_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dial_hargaActionPerformed

    private void dial_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dial_stockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dial_stockActionPerformed

    private void dial_asalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dial_asalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dial_asalActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
      Jdialog.dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void dial_kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dial_kategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dial_kategoriActionPerformed

    private void dial_jilidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dial_jilidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dial_jilidActionPerformed

    private void JTabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTabel1MouseClicked
        int index = JTabel1.getSelectedRow();
        TableModel model = JTabel1.getModel();
        kode_buku = model.getValueAt(index, 1).toString();
    }//GEN-LAST:event_JTabel1MouseClicked

    private void JdialogFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JdialogFocusLost
        Jdialog.dispose();
    }//GEN-LAST:event_JdialogFocusLost

    private void JdialogKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JdialogKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            Jdialog.setVisible(true);
        }
    }//GEN-LAST:event_JdialogKeyPressed

    private void jPanel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel1AncestorAdded
        try {
            // TODO add your handling code here:
            loadTabel();
            Jdialog();
        } catch (SQLException ex) {
            Logger.getLogger(Buku.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jPanel1AncestorAdded

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        try {
            // TODO add your handling code here:
            loadTabel();
        } catch (SQLException ex) {
            Logger.getLogger(Buku.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formAncestorAdded

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        Jdialog.dispose();
    }//GEN-LAST:event_formMouseClicked

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        String keyword = txt_search.getText().trim();
        String sql = "SELECT * FROM buku "
                + "WHERE No_buku LIKE '%" + keyword + "%' OR "
                + "kode_buku LIKE '%" + keyword + "%' OR "
                + "judul_buku LIKE '%" + keyword + "%' OR "
                + "jilid LIKE '%" + keyword + "%' OR "
                + "kategori LIKE '%" + keyword + "%' OR "
                + "pengarang LIKE '%" + keyword + "%' OR "
                + "lokasi LIKE '%" + keyword + "%' OR "
                + "kondisi_buku LIKE '%" + keyword + "%' OR "
                + "tahun_terbit LIKE '%" + keyword + "%' OR "
                + "asal_buku LIKE '%" + keyword + "%' OR "
                + "harga LIKE '%" + keyword + "%' OR "
                + "jumlah_stock LIKE '%" + keyword + "%'";

        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            // Creating a model to store the filtered data
            DefaultTableModel filteredModel = new DefaultTableModel();
            filteredModel.addColumn("No");
            filteredModel.addColumn("Kode Buku");
            filteredModel.addColumn("Judul Buku");
            filteredModel.addColumn("Jilid");
            filteredModel.addColumn("Kategori");
            filteredModel.addColumn("Pengarang");
            filteredModel.addColumn("Lokasi");
            filteredModel.addColumn("Kondisi");
            filteredModel.addColumn("Tahun Terbit");
            filteredModel.addColumn("Asal Buku");
            filteredModel.addColumn("Harga");
            filteredModel.addColumn("Stock");

            while (rs.next()) {
                filteredModel.addRow(new Object[]{
                    rs.getString("No_buku"),
                    rs.getString("kode_buku"),
                    rs.getString("judul_buku"),
                    rs.getString("jilid"),
                    rs.getString("kategori"),
                    rs.getString("pengarang"),
                    rs.getString("lokasi"),
                    rs.getString("kondisi_buku"),
                    rs.getString("tahun_terbit"),
                    rs.getString("asal_buku"),
                    rs.getString("harga"),
                    rs.getString("jumlah_stock")
                });
            }

            // Set the filtered model to the JTable
            JTabel1.setModel(filteredModel);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_txt_searchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTabel1;
    private javax.swing.JDialog Jdialog;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JTextField dial_asal;
    private javax.swing.JTextField dial_harga;
    private javax.swing.JTextField dial_jilid;
    private javax.swing.JTextField dial_judul;
    private javax.swing.JComboBox<String> dial_kategori;
    private javax.swing.JTextField dial_kode;
    private javax.swing.JComboBox<String> dial_kondisi;
    private javax.swing.JTextField dial_lokasi;
    private javax.swing.JTextField dial_pengarang;
    private javax.swing.JTextField dial_stock;
    private javax.swing.JTextField dial_tahun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
